# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'app' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for app
  pod 'R.swift'
  pod 'AmazonS3RequestManager'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
end
